/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aws.access.policy.test;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.sns.AmazonSNS;
import com.amazonaws.services.sns.AmazonSNSClient;

public class SNSAccessPolicyTest {
    public static void main(String[] args) {
        AmazonSNS snsClient = new AmazonSNSClient();
        snsClient.publish("topic", "hello");
    }
}
